version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: bk_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bk_network

  app:
    build: .
    env_file:
      - .env
    container_name: bk_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
    ports:
      - "3030:3000"
    working_dir: /app
    command: sh -c "npm run start"
    networks:
      - bk_network  

volumes:
  pgdata: 
 
networks:
  bk_network:
    driver: bridge 